/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmigosRouteImport } from './routes/amigos'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as DesarrolladoresRouteImport } from './routes/desarrolladores'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as TopRouteImport } from './routes/top'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as JuegosJuegoIdRouteImport } from './routes/juegos.$juegoId'
import { Route as JugarJuegoIdRouteImport } from './routes/jugar.$juegoId'
import { Route as UsuariosUsuarioIdRouteImport } from './routes/usuarios.$usuarioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmigosRoute = AmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const DesarrolladoresRoute = DesarrolladoresRouteImport.update({
  id: '/desarrolladores',
  path: '/desarrolladores',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosJuegoIdRoute = JuegosJuegoIdRouteImport.update({
  id: '/juegos/$juegoId',
  path: '/juegos/$juegoId',
  getParentRoute: () => rootRouteImport,
} as any)
const JugarJuegoIdRoute = JugarJuegoIdRouteImport.update({
  id: '/jugar/$juegoId',
  path: '/jugar/$juegoId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosUsuarioIdRoute = UsuariosUsuarioIdRouteImport.update({
  id: '/usuarios/$usuarioId',
  path: '/usuarios/$usuarioId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/biblioteca': typeof BibliotecaRoute
  '/desarrolladores': typeof DesarrolladoresRoute
  '/perfil': typeof PerfilRoute
  '/top': typeof TopRoute
  '/wishlist': typeof WishlistRoute
  '/juegos/$juegoId': typeof JuegosJuegoIdRoute
  '/jugar/$juegoId': typeof JugarJuegoIdRoute
  '/usuarios/$usuarioId': typeof UsuariosUsuarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/biblioteca': typeof BibliotecaRoute
  '/desarrolladores': typeof DesarrolladoresRoute
  '/perfil': typeof PerfilRoute
  '/top': typeof TopRoute
  '/wishlist': typeof WishlistRoute
  '/juegos/$juegoId': typeof JuegosJuegoIdRoute
  '/jugar/$juegoId': typeof JugarJuegoIdRoute
  '/usuarios/$usuarioId': typeof UsuariosUsuarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/biblioteca': typeof BibliotecaRoute
  '/desarrolladores': typeof DesarrolladoresRoute
  '/perfil': typeof PerfilRoute
  '/top': typeof TopRoute
  '/wishlist': typeof WishlistRoute
  '/juegos/$juegoId': typeof JuegosJuegoIdRoute
  '/jugar/$juegoId': typeof JugarJuegoIdRoute
  '/usuarios/$usuarioId': typeof UsuariosUsuarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amigos'
    | '/biblioteca'
    | '/desarrolladores'
    | '/perfil'
    | '/top'
    | '/wishlist'
    | '/juegos/$juegoId'
    | '/jugar/$juegoId'
    | '/usuarios/$usuarioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amigos'
    | '/biblioteca'
    | '/desarrolladores'
    | '/perfil'
    | '/top'
    | '/wishlist'
    | '/juegos/$juegoId'
    | '/jugar/$juegoId'
    | '/usuarios/$usuarioId'
  id:
    | '__root__'
    | '/'
    | '/amigos'
    | '/biblioteca'
    | '/desarrolladores'
    | '/perfil'
    | '/top'
    | '/wishlist'
    | '/juegos/$juegoId'
    | '/jugar/$juegoId'
    | '/usuarios/$usuarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmigosRoute: typeof AmigosRoute
  BibliotecaRoute: typeof BibliotecaRoute
  DesarrolladoresRoute: typeof DesarrolladoresRoute
  PerfilRoute: typeof PerfilRoute
  TopRoute: typeof TopRoute
  WishlistRoute: typeof WishlistRoute
  JuegosJuegoIdRoute: typeof JuegosJuegoIdRoute
  JugarJuegoIdRoute: typeof JugarJuegoIdRoute
  UsuariosUsuarioIdRoute: typeof UsuariosUsuarioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amigos': {
      id: '/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AmigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desarrolladores': {
      id: '/desarrolladores'
      path: '/desarrolladores'
      fullPath: '/desarrolladores'
      preLoaderRoute: typeof DesarrolladoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/$juegoId': {
      id: '/juegos/$juegoId'
      path: '/juegos/$juegoId'
      fullPath: '/juegos/$juegoId'
      preLoaderRoute: typeof JuegosJuegoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugar/$juegoId': {
      id: '/jugar/$juegoId'
      path: '/jugar/$juegoId'
      fullPath: '/jugar/$juegoId'
      preLoaderRoute: typeof JugarJuegoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/$usuarioId': {
      id: '/usuarios/$usuarioId'
      path: '/usuarios/$usuarioId'
      fullPath: '/usuarios/$usuarioId'
      preLoaderRoute: typeof UsuariosUsuarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmigosRoute: AmigosRoute,
  BibliotecaRoute: BibliotecaRoute,
  DesarrolladoresRoute: DesarrolladoresRoute,
  PerfilRoute: PerfilRoute,
  TopRoute: TopRoute,
  WishlistRoute: WishlistRoute,
  JuegosJuegoIdRoute: JuegosJuegoIdRoute,
  JugarJuegoIdRoute: JugarJuegoIdRoute,
  UsuariosUsuarioIdRoute: UsuariosUsuarioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
